### ISSUE TITLE
arg. error

### ISSUE THREAD

**Issue by rslprpr** [casperkaae/parmesan#37]
Hello, I have problem in running, I've tried this command :+1:
`sudo python mnist_ladder.py -lambdas 1,10,0.1,0.1,0.1,0.1,0.1` but it gives me this error 

>  h6: (200, 10)
    y_weights_decoder: (100, 10)
    Traceback (most recent call last):
    File "mnist_ladder.py", line 238, in
    h6_dec, name='dec_normalize6'), name='dec_scale6')
    File "/home/homa/parmesan/parmesan/layers/normalize.py", line 61, in init
    super(NormalizeLayer, self).init(incoming, *kwargs)
    File "/usr/local/lib/python2.7/dist-packages/Lasagne-0.1-py2.7.egg/lasagne/layers/base.py", line 38, in init
    self.input_shape = incoming.output_shape
    File "/usr/local/lib/python2.7/dist-packages/Lasagne-0.1-py2.7.egg/lasagne/layers/base.py", line 52, in output_shape
    return self.get_output_shape_for(self.input_shape)
    File "/usr/local/lib/python2.7/dist-packages/Lasagne-0.1-py2.7.egg/lasagne/layers/shape.py", line 380, in get_output_shape_for
    range(self.slice.indices(input_shape[self.axis])))
    TypeError: 'NoneType' object cannot be interpreted as an index

Do you have any idea what am I doing wrong in giving args? I just wanna try it for one iteration to see how does it work.

Thanks

**Comment by skaae** [comment]
Did you change any thing else? It seems to work fine for me. 

ps. I don't think you need to run python with `sudo` :)

**Comment by rslprpr** [comment]
No I did not change anything at all! ... by the way I need to put `sudo` there for writing the results.

**Comment by skaae** [comment]
I tried to update Lasagne and Parmesan to the latest versions. I still don't have any problems. Are you sure that Lasagne and Parmesan are updated?

**Comment by skaae** [comment]
ps. Parmesan is only tested using python 2.7. I don't know if there is any problems with python 3

**Comment by rslprpr** [comment]
I updated the Lasagne and it works perfectly! thanks

**Comment by casperkaae** [comment]
closed #37
