### ISSUE TITLE
TypeError: 'NoneType' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by rslprpr** [casperkaae/parmesan#44]
I have tried to run the mnist_ladder.py example without changing anything, it gives me following error. Would you please tell me what I'm doing wrong?

`Lambdas:  [1000.0, 10.0, 0.1, 0.1, 0.1, 0.1, 0.1]
h6: (200, 10)
y_weights_decoder: (0, 10)
Traceback (most recent call last):
  File "mnist_ladder.py", line 268, in <module>
    h6_dec, name='dec_normalize6'), name='dec_scale6')
  File "/home/usr/parmesan/parmesan/layers/normalize.py", line 61, in __init__
    super(NormalizeLayer, self).__init__(incoming, **kwargs)
  File "/home/usr/venv/local/lib/python2.7/site-packages/Lasagne-0.1-py2.7.egg/lasagne/layers/base.py", line 38, in __init__
    self.input_shape = incoming.output_shape
  File "/home/usr/venv/local/lib/python2.7/site-packages/Lasagne-0.1-py2.7.egg/lasagne/layers/base.py", line 52, in output_shape
    return self.get_output_shape_for(self.input_shape)
  File "/home/usr/venv/local/lib/python2.7/site-packages/Lasagne-0.1-py2.7.egg/lasagne/layers/shape.py", line 380, in get_output_shape_for
    range(*self.slice.indices(input_shape[self.axis])))
TypeError: 'NoneType' object cannot be interpreted as an index
`

**Comment by casperkaae** [comment]
Sounds like the same error as here #37 

you need to update Lasagne i think (see http://lasagne.readthedocs.io/en/latest/user/installation.html#bleeding-edge-version)

**Comment by rslprpr** [comment]
Yes it happend because of old version of Lasagne. Thanks
